services:
  pasang:
    image: nginx:alpine
    volumes:
      - .:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pasang.rule=Host(`pasang.pramesh.one`)"
      - "traefik.http.routers.pasang.entrypoints=websecure"
      - "traefik.http.routers.pasang.tls.certresolver=letsencrypt"
      - "traefik.http.services.pasang.loadbalancer.server.port=80"
    networks:
      - pasang-net

networks:
  pasang-net:
    external: true
